language: node_js
node_js:
  - node

cache: npm

install: npm i

jobs:
  include:
    - stage: build
      script: 
        - npm run build
        - npm run test
        - npm audit
        - npm run lint
        - npm run publish-coverage